name: app

type: 'php:8.3'

disk: 256

relationships:
  mariadb: 'mariadb:mysql'

mounts:
  'web/uploads':
    source: local
    source_path: uploads
  'var/log':
    source: local
    source_path: log
  'var/cache':
    source: local
    source_path: cache

hooks:
  build: |
    php bin/console cache:clear --env=prod
  deploy:
    - |
      platform variable:set --level environment --name env:MY_DATABASE_URL --value "$DATABASE_URL" --visible-build false --visible-runtime true --environment $PLATFORM_BRANCH

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"