name: app

type: 'php:8.3'

disk: 256

relationships:
  mariadb: 'mariadb:mysql'

variables:
  env:
    APP_SECRET: '629728183e4974a89834b4b48ed47d77'
    APP_ENV: 'dev'
    APP_DEBUG: '1'

mounts:
  'web/uploads':
    source: local
    source_path: uploads
  'var/log':
    source: local
    source_path: log
  'var/cache':
    source: local
    source_path: cache

hooks:
  build: |
    php bin/console cache:clear --env=prod

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"