name: app

type: 'php:8.3'

disk: 256

relationships:
  mariadb: 'mariadb:mysql'

mounts:
  'web/uploads':
    source: local
    source_path: uploads
  'var/log':
    source: local
    source_path: log
  'var/cache':
    source: local
    source_path: cache

hooks:
  build: |
    php bin/console cache:clear --env=prod

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"
  commands:
    start: |
      export DATABASE_URL=$(platform relationships | base64 --decode | jq -r '.database[0] | "mysql://\(.username):\(.password)@\(.host):\(.port)/\(.path)?serverVersion=mariadb-11.4"')