name: app

type: 'php:8.3'

disk: 256

relationships:
  mariadb: 'mariadb:mysql'

variables:
  env:
    DATABASE_URL: "mysql://${mariadb.username}:${mariadb.password}@${mariadb.host}:${mariadb.port}/${mariadb.path}"

mounts:
  'web/uploads':
    source: local
    source_path: uploads
  'var/log':
    source: local
    source_path: log
  'var/cache':
    source: local
    source_path: cache

hooks:
  build: |
    php bin/console cache:clear --env=prod

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"