name: app

type: 'php:8.3'

disk: 256

mounts:
  'web/uploads':
    source: local
    source_path: uploads
  'var/log':
    source: local
    source_path: log

relationships:
  mariadb: 'mariadb:mysql'

hooks:
  build: |
    php bin/console cache:clear --env=prod
