name: app

type: 'php:8.3'

disk: 256

relationships:
  mariadb: 'mariadb:mysql'

variables:
  env:
    DATABASE_URL: '${env:DATABASE_URL}'
    MAILER_DSN: '${env:MAILER_DSN}'
    APP_SECRET: '${env:APP_SECRET}'
    APP_ENV: 'prod'
    APP_DEBUG: '1'

mounts:
  'web/uploads':
    source: local
    source_path: uploads
  'var/log':
    source: local
    source_path: log
  'var/cache':
    source: local
    source_path: cache

hooks:
  build: |
    php bin/console cache:clear --env=prod

web:
  locations:
    "/":
      root: "public"
      passthru: "/index.php"